### ISSUE TITLE
usage should show mendeley2zotero.py

### ISSUE THREAD

**Issue by rdiaz02** [flinz/mendeley2zotero#1]
In your usage you have `python exporter.py blablablab` but you should have `python mendeley2zotero.py blablabla`

**Comment by seeholza** [comment]
Yeah, and completely forgot to follow up on this.
Sorry for the delay, this is now addressed in https://github.com/flinz/mendeley2zotero/commit/bcb913371dc21e257a5baaa446959bb52ff68c4b
