### ISSUE TITLE
divide time by 1000 before creating timestamp

### ISSUE THREAD

**Issue by rdiaz02** [flinz/mendeley2zotero#2]
At least as of July 2015, Mendeley is storing the date as miliseconds since 1970. Therefore, line 97, 
`d_added = datetime.datetime.utcfromtimestamp(d_added)` should really be `d_added = datetime.datetime.utcfromtimestamp(d_added/1000)`

**Comment by seeholza** [comment]
Thanks for pointing this out. If you should fix it, please make a pull request.

**Comment by rdiaz02** [comment]
I'd do it, but I am not sure this is the case for all versions of Mendeley (OS, version of Mendeley, etc), and since I seem to be the only one to have pointed this out, I am hesitant to force a change that might break things.

**Comment by mim** [comment]
I found the same thing. I'm on Ubuntu 16.04 using Mendeley 1.17.13.

**Comment by seeholza** [comment]
Sorry for the delay. This was fixed in https://github.com/flinz/mendeley2zotero/pull/7
