### ISSUE TITLE
OperationalError

### ISSUE THREAD

**Issue by matrs** [flinz/mendeley2zotero#5]
Hi, 
When running this script, I'm getting an error. The error message points to an [OperationalError]( http://docs.sqlalchemy.org/en/latest/errors.html#error-e3q8 )  (I'm pasting it somewhere else because it's relatively long):
https://pastebin.com/GpwXthkZ

I don't know if it's about the database which is in some way corrupted or something else. One of the last lines reads:

`"Documents".year AS "Documents_year" \nFROM "Documents" \nWHERE "Documents".title = ?'] [parameters: (u"Fisher's Exact Test \xb7 Guide",)]`

So "Fisher's Exact Test \xb7 Guide" isn't a title of any document I have and I don't know to what document is referring to.

 it would be great if somebody can give me a hint about this.

**Comment by seeholza** [comment]
Sorry for the late reply. The pastebin has vanished by now.
Could be you have some special characters in the title that messes with the parsing..

If you don't find the "Fisher's.. " document locally, maybe check in the zotero online version at https://www.zotero.org
